### ISSUE TITLE
Install-Terraform must install the latest version if no given version

### ISSUE THREAD

**Issue by lktslionel** [pearcec/Invoke-Terraform#10]
### Acceptance tests

- [ ] `Given` No args, `When` I run the command `Install-Terraform` `Then` It should install the latest version of Terraform available
- [ ] `When` I run the command `Install-Terraform` with the version label "latest",  `Then` It should install the latest version of Terraform

**Comment by pearcec** [comment]
I was considering `-TFVersion 'latest'` or `-Lastest` as a second parameter set.  Using `-Lastest` keep the usage of TFVersion clean.

**Comment by pearcec** [comment]
Parameter set doesn't make sense.  Thinking removing mandatory grabs the latest for you.

**Comment by lktslionel** [comment]
The parameter `-Latest` looks great and more PowerShell-idiomatic.

**Comment by pearcec** [comment]
Trouble with the `-Latest` is making that default breaks [PSScriptAnalayzer](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/RuleDocumentation/AvoidDefaultValueSwitchParameter.md).  It encourages you to avoid default values on a switch.  I think leaving out the version going with the latest is good default behavior.
