### ISSUE TITLE
Getting 403 forbidden when using switch-terraform

### ISSUE THREAD

**Issue by Blankf** [pearcec/Invoke-Terraform#20]
**Describe the bug**
whenever i used switch-terraform cmdlet to switch to for example 1.1.2, i get the following error: Exception: Unable to request https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_SHA256SUMS.348FFC4C.sig

**To Reproduce**
1. Switch-Terraform -TFVersion 1.1.2
2. terraform -version

**Expected behavior**
It should install the version specified in the switch terraform and run the cmd.

**Output**
WARNING: Terraform version 1.1.2 not found.
Exception: Unable to request https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_SHA256SUMS.348FFC4C.sig

**Desktop (please complete the following information):**
 - OS: Windows 11, Powershell 7.2.1

**Additional context**
It seems they changed the sig files.
https://releases.hashicorp.com/terraform/1.1.2/

show:
terraform_1.1.2_SHA256SUMS.72D7468F.sig
terraform_1.1.2_SHA256SUMS.sig

**Comment by pearcec** [comment]
👋 Sorry I missed this. This is documented in the changelog with 0.5.1.  You need to update your HashiCorpPGPKeyId configuration. https://github.com/pearcec/Invoke-Terraform/blob/main/CHANGELOG.md#security
